### ISSUE TITLE
Core refactoring

### ISSUE THREAD

**Issue by KostyaZgara** [1337lawyers/web#34]
1. Integrate absolute paths
With absolute paths, we don't need to use "../../..". The path always will start from folder "src"

2. Ditch from Markdown pages
Seems it's overhead for creating even static pages. Mdx files confused between differently files https://prnt.sc/p6gv89

3. Switch to camelCase naming style, where if a file contains class it's mean that file name should begin from capital letter.

4. I'm really concerned about bundle size. 1mb it's very big, maybe need to investigate some dependencies. Identify which library might be unnecessary.

5. Before beginning to implement tasks such as https://github.com/1337lawyers/web/issues/31 need to create properly app skeleton: prepare layouts with headers and footers, get to know what pages expected in the future (for this purpose, we need to have wireframe). With wireframes, we can develop reusing and good components.

**Comment by shicholas** [comment]
Answering this piecemeal. I agree with number 1 and 3 and created PR #35 to address this.

With the absolute paths, I created new path helpers in both the `tsconfig.json` file and [the gatsby plugin module resolver](https://www.gatsbyjs.org/packages/gatsby-plugin-module-resolver/) settings so components can be referenced everywhere as `@components` and layouts as `@layouts`

With switching to camelcase, I agree the name of the export should match the file name. For JSX components, I opted to change the name into Pascal case since components are usually referred to like `Header`, `Footer` in templates. For the files in the `pages` directory, Gatsby uses the file names to create a static HTML file at that extension. This is why I use kebob-case instead of camelCase or snake_case because I think kebob-case looks better in URLs

**Comment by shicholas** [comment]
Regarding the second point about markdown pages, I'd like to keep the MDX files because I have other people I work with that know how to write markdown, but not code. Additionally, I like using Markdown for writing blog posts, which I hope to do a lot of here.

**Comment by shicholas** [comment]
Regarding bundle size, are you considering that Gatsby creates a bunch of individual bundles per page. For instance, there's a different bundle for the HTML that serves `/` vs `/blog` vs `/for-business`.  I wouldn't worry too much about bundle size at this point in the project, I believe that if we use this framework, the Gatsby team will figure it out.

**Comment by shicholas** [comment]
re: app skeleton, can we please start by copying the `Users`, `Products`, `Authentication`, and `Settings` pages from https://github.com/devias-io/react-material-dashboard ? using the latest material UI with the `makeStyles` helper and typescript? You can run that project locally and see it in action on `localhost:3000`

**Comment by shicholas** [comment]
I'll have time to update the styling from there once we have those basic pages done.

**Comment by shicholas** [comment]
@KostyaZgara is there more you want to address here? Or can I close?

**Comment by KostyaZgara** [comment]
@shicholas Yes, you can close this issue.

**Comment by shicholas** [comment]
cool thanks
